#!/usr/bin/env python3
"""
Extract torch.ops._C schema strings from vLLM's C++ source and write them to
vllm_fl/ops/_C_ops_schemas.py.

Run this script whenever vLLM is upgraded so the bundled schemas stay in sync:

    python tools/generate_op_schemas.py

The script auto-detects the vLLM source tree from the installed package. If
vLLM was installed in editable mode the csrc/ directory is next to the package;
otherwise pass the path explicitly:

    python tools/generate_op_schemas.py /path/to/vllm
"""

import re
import sys
from pathlib import Path


def extract_schemas(vllm_root: Path) -> list[str]:
    source_files = [
        vllm_root / "csrc" / "torch_bindings.cpp",
        vllm_root / "csrc" / "libtorch_stable" / "torch_bindings.cpp",
    ]

    pattern = re.compile(
        r'ops\.def\(\s*\n?\s*"((?:[^"]*"\s*\n?\s*")*[^"]*)"', re.DOTALL
    )
    schemas: list[str] = []
    seen: set[str] = set()

    for path in source_files:
        if not path.exists():
            continue
        content = path.read_text()
        for match in pattern.finditer(content):
            raw = match.group(1)
            schema = re.sub(r'"\s*\n?\s*"', "", raw).strip()
            schema = re.sub(r"\s+", " ", schema)
            if "(" not in schema:
                continue
            full_name = schema.split("(")[0]
            if full_name not in seen:
                seen.add(full_name)
                schemas.append(schema)

    return schemas


def main() -> None:
    if len(sys.argv) > 1:
        vllm_root = Path(sys.argv[1])
    else:
        import vllm

        vllm_root = Path(vllm.__file__).resolve().parent.parent

    schemas = extract_schemas(vllm_root)
    if not schemas:
        print(f"ERROR: no schemas found under {vllm_root}/csrc/", file=sys.stderr)
        sys.exit(1)

    out = (
        Path(__file__).resolve().parent.parent / "vllm_fl" / "ops" / "_C_ops_schemas.py"
    )
    lines = [
        "# Auto-generated by tools/generate_op_schemas.py — do not edit.",
        "",
        "SCHEMAS: list[str] = [",
    ]
    for s in schemas:
        lines.append(f"    {repr(s)},")
    lines.append("]")
    lines.append("")
    out.write_text("\n".join(lines))
    print(f"Wrote {len(schemas)} schemas to {out}")


if __name__ == "__main__":
    main()
